// Auto-generated by mix ash_dispatch.gen.counter_types
// Do not edit manually
// Generated at: 2025-11-21T00:41:05.369933Z

export type UngroupedCounters = {
  unread_notifications: number;
};

export type AllCounters = UngroupedCounters;

export const COUNTERS = {
  notification: {
    unread_notifications: "unread_notifications",
  },
} as const;

export const COUNTER_METADATA = {
  unread_notifications: {
    audience: "user",
    global: false,
    invalidates: ["notifications"],
  },
} as const;

export type CounterName = "unread_notifications";

export function isValidCounter(name: string): name is CounterName {
  return name in COUNTER_METADATA;
}
