defmodule AshDispatch.Resource.Transformers.InjectDispatchChangesTest do
  use ExUnit.Case, async: true

  alias AshDispatch.Changes.DispatchEvent

  describe "event module resolution" do
    setup do
      Application.put_env(:ash_dispatch_test, :ash_domains, [AshDispatch.Test.Domain])

      on_exit(fn ->
        Application.delete_env(:ash_dispatch_test, :ash_domains)
      end)

      :ok
    end

    test "explicit module in DSL is used (override)" do
      # AshDispatch.Test.Order has explicit module: AshDispatch.Test.Events.OrderCreated
      # The transformer should use that module, not derive a new one

      # Get the action from the compiled resource
      action = Ash.Resource.Info.action(AshDispatch.Test.Order, :create)

      # Find the DispatchEvent change
      dispatch_change =
        Enum.find(action.changes, fn change ->
          match?(%Ash.Resource.Change{change: {DispatchEvent, _}}, change)
        end)

      assert dispatch_change != nil

      {DispatchEvent, opts} = dispatch_change.change
      event_config = Keyword.get(opts, :event_config)

      # Should use the explicit module, not a derived one
      assert event_config.module == AshDispatch.Test.Events.OrderCreated
    end

    test "inline event gets nil module initially (before codegen)" do
      # AshDispatch.Test.Ticket.created has no explicit module
      # Since the derived module doesn't exist yet, it should be nil

      action = Ash.Resource.Info.action(AshDispatch.Test.Ticket, :create)

      dispatch_change =
        Enum.find(action.changes, fn change ->
          match?(%Ash.Resource.Change{change: {DispatchEvent, _}}, change)
        end)

      assert dispatch_change != nil

      {DispatchEvent, opts} = dispatch_change.change
      event_config = Keyword.get(opts, :event_config)

      # Module should be nil since derived module doesn't exist yet
      # (it would be generated by mix ash.codegen)
      # The derived module would be: AshDispatchTest.Test.Events.Created.Event
      # But since it doesn't exist, we get nil
      assert event_config.module == nil
    end

    test "event_config contains domain and resource_name for template resolution" do
      action = Ash.Resource.Info.action(AshDispatch.Test.Ticket, :create)

      dispatch_change =
        Enum.find(action.changes, fn change ->
          match?(%Ash.Resource.Change{change: {DispatchEvent, _}}, change)
        end)

      {DispatchEvent, opts} = dispatch_change.change
      event_config = Keyword.get(opts, :event_config)

      # Should have domain and resource_name for convention-based template paths
      assert event_config.domain == "test"
      assert event_config.resource_name == "ticket"
    end

    test "event_id is correctly generated" do
      action = Ash.Resource.Info.action(AshDispatch.Test.Ticket, :create)

      dispatch_change =
        Enum.find(action.changes, fn change ->
          match?(%Ash.Resource.Change{change: {DispatchEvent, _}}, change)
        end)

      {DispatchEvent, opts} = dispatch_change.change
      event_id = Keyword.get(opts, :event_id)

      # Event ID format: {resource_name}.{event_name}
      assert event_id == "ticket.created"
    end

    test "channels are passed through to event_config" do
      action = Ash.Resource.Info.action(AshDispatch.Test.Ticket, :assign)

      dispatch_change =
        Enum.find(action.changes, fn change ->
          match?(%Ash.Resource.Change{change: {DispatchEvent, _}}, change)
        end)

      {DispatchEvent, opts} = dispatch_change.change
      event_config = Keyword.get(opts, :event_config)

      # assigned event has 2 channels: in_app and email
      assert length(event_config.channels) == 2

      transports = Enum.map(event_config.channels, fn channel ->
        cond do
          is_map(channel) -> Map.get(channel, :transport)
          is_list(channel) -> Keyword.get(channel, :transport)
        end
      end)

      assert :in_app in transports
      assert :email in transports
    end

    test "content is passed through to event_config" do
      action = Ash.Resource.Info.action(AshDispatch.Test.Ticket, :create)

      dispatch_change =
        Enum.find(action.changes, fn change ->
          match?(%Ash.Resource.Change{change: {DispatchEvent, _}}, change)
        end)

      {DispatchEvent, opts} = dispatch_change.change
      event_config = Keyword.get(opts, :event_config)

      # created event has content defined
      assert event_config.content[:notification_title] == "Ticket Created"
      assert event_config.content[:notification_message] == "Ticket {{title}} was created"
    end
  end

  describe "derive_event_module_name" do
    # Test the module name derivation convention
    # This tests the expected naming convention that transformer uses

    test "derives correct module name convention" do
      # The transformer uses this convention:
      # {App}.{Domain}.Events.{EventName}.Event
      # where App comes from the resource module

      # For AshDispatch.Test.Ticket with event :created
      # Resource: AshDispatch.Test.Ticket
      # App: AshDispatch (first module segment)
      # Domain: test (second-to-last segment, underscored)
      # Event: created

      # Expected: AshDispatch.Test.Events.Created.Event
      # (Note: actual derivation uses the extracted domain_name from transformer)

      # This test verifies the convention matches what generator expects
      expected_module = AshDispatch.Test.Events.Created.Event

      # The module should follow this pattern
      assert Module.split(expected_module) == ["AshDispatch", "Test", "Events", "Created", "Event"]
    end
  end
end
