defmodule AshDispatch.Resource.Transformers.InjectDispatchChangesTest do
  @moduledoc """
  Tests for `InjectDispatchChanges` transformer.

  Post-retrofit (commit `79dc5db`), the transformer no longer injects
  `change AshDispatch.Changes.DispatchEvent` per action — it persists
  per-action event_config into dsl_state under
  `:ash_dispatch_dispatch_events` and registers `AshDispatch.Notifier`
  in `:simple_notifiers`. These assertions read the persisted state
  via `AshDispatch.Notifier.Info` rather than introspecting
  `action.changes`.

  See `AshDispatch.Notifier` moduledoc for the architectural
  rationale (Ash.transaction tx-semantics — phantom-fire-on-rollback
  elimination via `Ash.Notifier`'s commit-deferred mechanism).
  """

  # Disable async because tests depend on Application config set in test_helper.exs
  use ExUnit.Case, async: false

  alias AshDispatch.Notifier
  alias AshDispatch.Notifier.Info

  describe "notifier registration" do
    test "InjectDispatchChanges registers AshDispatch.Notifier on resources with dispatch events" do
      # Resources with `dispatch do event ... end` blocks should have
      # AshDispatch.Notifier registered as a simple_notifier.
      notifiers = Ash.Resource.Info.notifiers(AshDispatch.Test.Ticket)
      assert Notifier in notifiers
    end

    test "registration is idempotent — Order also has Notifier exactly once" do
      notifiers = Ash.Resource.Info.notifiers(AshDispatch.Test.Order)
      assert Notifier in notifiers
      assert Enum.count(notifiers, &(&1 == Notifier)) == 1
    end
  end

  describe "event module resolution" do
    test "explicit module in DSL is used (override)" do
      # AshDispatch.Test.Order has explicit module: AshDispatch.Test.Events.OrderCreated
      # The transformer should persist that module, not derive a new one.
      [event_config] = Info.dispatch_events_for(AshDispatch.Test.Order, :create)

      assert event_config.event_config.module == AshDispatch.Test.Events.OrderCreated
    end

    test "inline event gets nil module initially (before codegen)" do
      # AshDispatch.Test.Ticket.created has no explicit module.
      # Since the derived module doesn't exist yet, it should be nil.
      [event_config] = Info.dispatch_events_for(AshDispatch.Test.Ticket, :create)

      # Module should be nil since derived module doesn't exist yet
      # (it would be generated by mix ash.codegen).
      assert event_config.event_config.module == nil
    end
  end

  describe "persisted event_config shape" do
    test "event_config contains domain and resource_name for template resolution" do
      [event_config] = Info.dispatch_events_for(AshDispatch.Test.Ticket, :create)

      assert event_config.event_config.domain == "test"
      assert event_config.event_config.resource_name == "ticket"
    end

    test "event_id is correctly generated" do
      [event_config] = Info.dispatch_events_for(AshDispatch.Test.Ticket, :create)

      # Event ID format: {resource_name}.{event_name}
      assert event_config.event_id == "ticket.created"
    end

    test "channels are passed through to event_config" do
      # The :assign action triggers the :assigned event which has 2 channels.
      [event_config] = Info.dispatch_events_for(AshDispatch.Test.Ticket, :assign)

      assert length(event_config.event_config.channels) == 2

      transports =
        Enum.map(event_config.event_config.channels, fn channel ->
          cond do
            is_map(channel) -> Map.get(channel, :transport)
            is_list(channel) -> Keyword.get(channel, :transport)
          end
        end)

      assert :in_app in transports
      assert :email in transports
    end

    test "content is passed through to event_config" do
      [event_config] = Info.dispatch_events_for(AshDispatch.Test.Ticket, :create)

      assert event_config.event_config.content[:notification_title] == "Ticket Created"

      assert event_config.event_config.content[:notification_message] ==
               "Ticket {{title}} was created"
    end

    test "include_actor_as is passed through to event_config" do
      # :assign triggers :assigned which sets `include_actor_as: :assigned_by`.
      [event_config] = Info.dispatch_events_for(AshDispatch.Test.Ticket, :assign)

      assert event_config.event_config.include_actor_as == :assigned_by
    end

    test "data_key is passed through to event_config" do
      [event_config] = Info.dispatch_events_for(AshDispatch.Test.Ticket, :assign)

      assert event_config.event_config.data_key == :ticket
    end

    test "include_actor_as defaults to nil when not specified" do
      [event_config] = Info.dispatch_events_for(AshDispatch.Test.Ticket, :create)

      assert event_config.event_config.include_actor_as == nil
    end
  end

  describe "per-action lookup" do
    test "actions without registered events return []" do
      # :read on Ticket has no event triggered_on it.
      assert Info.dispatch_events_for(AshDispatch.Test.Ticket, :read) == []
    end

    test "all_dispatch_events/1 returns the full action_name => [event_config] map" do
      events = Info.all_dispatch_events(AshDispatch.Test.Ticket)

      # Ticket has events on :create, :assign, :close (escalated).
      assert is_map(events)
      assert Map.has_key?(events, :create)
      assert Map.has_key?(events, :assign)
      assert Map.has_key?(events, :close)
    end

    test "resources without `dispatch do` blocks return empty maps" do
      # CounterTestResource (test/support/test_resources.ex) has no
      # dispatch block. Its dispatch_events map should be empty.
      assert Info.all_dispatch_events(AshDispatch.Test.CounterTestResource) == %{}
    end
  end

  describe "module name derivation convention" do
    test "derives correct module name convention" do
      # Convention: {App}.{Domain}.Events.{EventName}.Event
      # For AshDispatch.Test.Ticket with event :created — expected
      # AshDispatch.Test.Events.Created.Event.
      expected_module = AshDispatch.Test.Events.Created.Event

      assert Module.split(expected_module) == [
               "AshDispatch",
               "Test",
               "Events",
               "Created",
               "Event"
             ]
    end
  end
end
