defmodule Mix.Tasks.AshDispatch.Gen.CounterTypes do
  @moduledoc """
  Generates TypeScript types and constants for AshDispatch counters.

  Discovers counter definitions from all resources using AshDispatch and generates
  TypeScript type definitions grouped by their `group` option.

  ## Usage

      # Generate counter types for all domains
      mix ash_dispatch.gen.counter_types

      # Specify output path
      mix ash_dispatch.gen.counter_types --output lib/my_app_web/static/js/counters.ts

      # Generate for specific domain only
      mix ash_dispatch.gen.counter_types --only MyApp.Orders

  ## Output

  Generates a TypeScript file with:
  - Type definitions for each counter group
  - A `COUNTERS` constant object with all counter names
  - Helper functions for type-safe counter access

  ## Example Output

      // Auto-generated by mix ash_dispatch.gen.counter_types
      // Do not edit manually

      export type OrderCounters = {
        pending_orders: number;
        processing_orders: number;
      };

      export type TicketCounters = {
        open_tickets: number;
        processing_tickets: number;
      };

      export type AllCounters = OrderCounters & TicketCounters;

      export const COUNTERS = {
        orders: {
          pending_orders: "pending_orders",
          processing_orders: "processing_orders",
        },
        tickets: {
          open_tickets: "open_tickets",
          processing_tickets: "processing_tickets",
        },
      } as const;

  ## Integration

  Use in your frontend:

      import { COUNTERS, type AllCounters } from "./counters";

      // Type-safe counter access
      const pendingCount = counters[COUNTERS.orders.pending_orders];
  """

  use Mix.Task

  @shortdoc "Generate TypeScript types for AshDispatch counters"

  @switches [
    output: :string,
    only: :string
  ]

  @aliases [
    o: :output,
    d: :only
  ]

  def run(args) do
    Mix.Task.run("compile")
    Mix.Task.reenable("ash_dispatch.gen.counter_types")

    {opts, _} = OptionParser.parse!(args, strict: @switches, aliases: @aliases)

    output_path = Keyword.get(opts, :output, "priv/static/counters.ts")
    only_domain = Keyword.get(opts, :only)

    # Get all Ash domains
    domains =
      if only_domain do
        [Module.concat([only_domain])]
      else
        Application.loaded_applications()
        |> Enum.flat_map(fn {app, _, _} ->
          Application.get_env(app, :ash_domains, [])
        end)
        |> Enum.uniq()
      end

    if Enum.empty?(domains) do
      Mix.shell().error(
        "No Ash domains found. Make sure domains are configured in your app config."
      )

      Mix.shell().info("Example: config :my_app, ash_domains: [MyApp.Accounts, MyApp.Orders]")
    else
      counters = discover_counters(domains)

      if Enum.empty?(counters) do
        Mix.shell().info("No counters found in domains.")
      else
        typescript = generate_typescript(counters)

        # Ensure output directory exists
        output_path
        |> Path.dirname()
        |> File.mkdir_p!()

        File.write!(output_path, typescript)
        Mix.shell().info("✓ Generated counter types: #{output_path}")

        # Print summary
        grouped = group_counters(counters)
        total = length(counters)
        groups = map_size(grouped)
        Mix.shell().info("  #{total} counters in #{groups} groups")
      end
    end
  end

  defp discover_counters(domains) do
    domains
    |> Enum.flat_map(&Ash.Domain.Info.resources/1)
    |> Enum.filter(&uses_ash_dispatch?/1)
    |> Enum.flat_map(&extract_counters/1)
  end

  defp uses_ash_dispatch?(resource) do
    AshDispatch.Resource in Spark.extensions(resource)
  end

  defp extract_counters(resource) do
    # Get resource name for namespacing (e.g., "cart_item" from Magasin.Catalog.CartItem)
    resource_name =
      resource
      |> Module.split()
      |> List.last()
      |> Macro.underscore()

    case Spark.Dsl.Extension.get_entities(resource, [:counters]) do
      [] ->
        []

      counters ->
        Enum.map(counters, fn counter ->
          %{
            name: counter.counter_name || counter.name,
            source: resource_name,
            group: counter.group || :ungrouped,
            audience: counter.audience,
            global?: Map.get(counter, :global?, false),
            invalidates: counter.invalidates || []
          }
        end)
    end
  rescue
    _ -> []
  end

  # Group by source resource for COUNTERS object
  defp group_by_source(counters) do
    Enum.group_by(counters, & &1.source)
  end

  # Deduplicate for types (by counter name)
  defp unique_counters(counters) do
    Enum.uniq_by(counters, & &1.name)
  end

  # Merge metadata for counters defined in multiple resources
  # - Union of invalidates
  # - Validate audience consistency
  # - Track all sources
  defp merge_counter_metadata(counters) do
    counters
    |> Enum.group_by(& &1.name)
    |> Enum.map(fn {name, instances} ->
      # Get all unique sources
      sources = instances |> Enum.map(& &1.source) |> Enum.uniq() |> Enum.sort()

      # Merge invalidates (union)
      invalidates =
        instances
        |> Enum.flat_map(& &1.invalidates)
        |> Enum.uniq()
        |> Enum.sort()

      # Validate audience consistency
      audiences = instances |> Enum.map(& &1.audience) |> Enum.uniq()
      audience = List.first(audiences)

      if length(audiences) > 1 do
        Mix.shell().error(
          "Warning: Counter '#{name}' has inconsistent audiences across resources: #{inspect(audiences)}"
        )
      end

      # Validate global consistency
      globals = instances |> Enum.map(& &1.global?) |> Enum.uniq()

      if length(globals) > 1 do
        Mix.shell().error(
          "Warning: Counter '#{name}' has inconsistent global? values across resources"
        )
      end

      # Get group from first instance (should be consistent)
      group = List.first(instances).group

      %{
        name: name,
        group: group,
        audience: audience,
        invalidates: invalidates,
        sources: sources
      }
    end)
  end

  defp group_counters(counters) do
    Enum.group_by(counters, & &1.group)
  end

  defp generate_typescript(counters) do
    # Deduplicate counters for types
    unique = unique_counters(counters)
    grouped = group_counters(unique)

    # Merge metadata for counters defined in multiple resources
    merged_metadata = merge_counter_metadata(counters)

    # Group by source resource for COUNTERS object
    by_source = group_by_source(counters)

    header = """
    // Auto-generated by mix ash_dispatch.gen.counter_types
    // Do not edit manually
    // Generated at: #{DateTime.utc_now() |> DateTime.to_iso8601()}

    """

    # Generate type definitions for each group (deduplicated)
    type_defs =
      grouped
      |> Enum.sort_by(fn {group, _} -> to_string(group) end)
      |> Enum.map(fn {group, group_counters} ->
        type_name = group_type_name(group)

        fields =
          Enum.map_join(group_counters, "\n", fn c ->
            "  #{c.name}: number;"
          end)

        """
        export type #{type_name} = {
        #{fields}
        };
        """
      end)
      |> Enum.join("\n")

    # Generate combined type
    all_types =
      grouped
      |> Map.keys()
      |> Enum.sort_by(&to_string/1)
      |> Enum.map(&group_type_name/1)
      |> Enum.join(" & ")

    combined_type = """
    export type AllCounters = #{all_types};
    """

    # Generate default counters (all initialized to 0)
    default_counter_fields =
      unique
      |> Enum.map(fn c -> "  #{c.name}: 0," end)
      |> Enum.join("\n")

    default_counters = """
    /**
     * Default counter values (all initialized to 0).
     * Use in your store initialization.
     */
    export const DEFAULT_COUNTERS: AllCounters = {
    #{default_counter_fields}
    };
    """

    # Generate counter names constant - grouped by SOURCE RESOURCE
    # This shows cart.cart_items and cart_item.cart_items both pointing to "cart_items"
    counter_const =
      by_source
      |> Enum.sort_by(fn {source, _} -> source end)
      |> Enum.map(fn {source, source_counters} ->
        fields =
          Enum.map_join(source_counters, "\n", fn c ->
            "    #{c.name}: \"#{c.name}\","
          end)

        "  #{source}: {\n#{fields}\n  },"
      end)
      |> Enum.join("\n")

    counters_object = """
    export const COUNTERS = {
    #{counter_const}
    } as const;
    """

    # Generate counter metadata (merged from all sources)
    metadata_entries =
      merged_metadata
      |> Enum.map(fn c ->
        invalidates_str = c.invalidates |> Enum.map(fn i -> "\"#{i}\"" end) |> Enum.join(", ")
        sources_str = c.sources |> Enum.map(fn s -> "\"#{s}\"" end) |> Enum.join(", ")

        "  #{c.name}: {\n    audience: \"#{c.audience}\",\n    invalidates: [#{invalidates_str}],\n    sources: [#{sources_str}],\n  },"
      end)
      |> Enum.join("\n")

    metadata = """
    export const COUNTER_METADATA = {
    #{metadata_entries}
    } as const;
    """

    # Generate helper type for counter names (deduplicated)
    counter_names =
      unique
      |> Enum.map(fn c -> "\"#{c.name}\"" end)
      |> Enum.join(" | ")

    # Generate camelCase accessor type and function
    camel_case_fields =
      unique
      |> Enum.map(fn c ->
        camel = snake_to_camel(to_string(c.name))
        {camel, c.name}
      end)

    accessor_type_fields =
      camel_case_fields
      |> Enum.map(fn {camel, _snake} -> "  #{camel}: number;" end)
      |> Enum.join("\n")

    accessor_impl =
      camel_case_fields
      |> Enum.map(fn {camel, snake} -> "    #{camel}: counters.#{snake}," end)
      |> Enum.join("\n")

    accessor_helper = """
    export type CounterName = #{counter_names};

    export function isValidCounter(name: string): name is CounterName {
      return name in COUNTER_METADATA;
    }

    /**
     * Type for camelCase counter accessors.
     * Use with getCounterAccessors() or in your useCounters hook.
     */
    export type CounterAccessors = {
    #{accessor_type_fields}
    };

    /**
     * Convert snake_case counters to camelCase accessors.
     * Auto-generated from counter definitions.
     *
     * @example
     * ```tsx
     * // In your useCounters hook:
     * export function useCounters() {
     *   const counters = useCounterStore((state) => state.counters)
     *   return {
     *     ...getCounterAccessors(counters),
     *     counters,
     *   }
     * }
     * ```
     */
    export function getCounterAccessors(counters: AllCounters): CounterAccessors {
      return {
    #{accessor_impl}
      };
    }
    """

    header <>
      type_defs <>
      "\n" <>
      combined_type <>
      "\n" <>
      default_counters <> "\n" <> counters_object <> "\n" <> metadata <> "\n" <> accessor_helper
  end

  defp snake_to_camel(string) do
    [first | rest] = String.split(string, "_")
    first <> Enum.map_join(rest, "", &String.capitalize/1)
  end

  defp group_type_name(:ungrouped), do: "UngroupedCounters"

  defp group_type_name(group) do
    group
    |> to_string()
    |> Macro.camelize()
    |> Kernel.<>("Counters")
  end
end
